/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GitSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/git/executor.ts
var import_child_process = require("child_process");
var import_util = require("util");
var execAsync = (0, import_util.promisify)(import_child_process.exec);
var GitExecutor = class {
  constructor(gitPath = "git", workingDir) {
    this.gitPath = gitPath;
    this.workingDir = workingDir;
  }
  /**
   * Execute a git command
   */
  async run(command) {
    try {
      const result = await execAsync(`${this.gitPath} ${command}`, {
        cwd: this.workingDir,
        maxBuffer: 50 * 1024 * 1024,
        // 50MB buffer
        timeout: 12e4
        // 2 minute timeout
      });
      return result;
    } catch (error) {
      const gitError = new Error(error.message);
      gitError.code = error.code;
      gitError.stderr = error.stderr || "";
      gitError.stdout = error.stdout || "";
      throw gitError;
    }
  }
  /**
   * Check if git is available
   */
  async isGitAvailable() {
    try {
      await execAsync(`${this.gitPath} --version`);
      return true;
    } catch (e) {
      return false;
    }
  }
  /**
   * Check if current directory is a git repository
   */
  async isRepo() {
    try {
      await this.run("rev-parse --is-inside-work-tree");
      return true;
    } catch (e) {
      return false;
    }
  }
  /**
   * Initialize a new git repository
   */
  async init() {
    await this.run("init");
  }
  /**
   * Get current branch name
   */
  async getCurrentBranch() {
    const result = await this.run("rev-parse --abbrev-ref HEAD");
    return result.stdout.trim();
  }
  /**
   * Get remote name (usually 'origin')
   */
  async getRemoteName() {
    try {
      const result = await this.run("remote");
      const remotes = result.stdout.trim().split("\n").filter(Boolean);
      return remotes.includes("origin") ? "origin" : remotes[0] || null;
    } catch (e) {
      return null;
    }
  }
  /**
   * Get current remote URL
   */
  async getRemoteUrl() {
    try {
      const remote = await this.getRemoteName();
      if (!remote)
        return null;
      const result = await this.run(`remote get-url ${remote}`);
      return result.stdout.trim();
    } catch (e) {
      return null;
    }
  }
  /**
   * Fetch from remote
   */
  async fetch() {
    const remote = await this.getRemoteName();
    if (remote) {
      await this.run(`fetch ${remote}`);
    }
  }
  /**
   * Get detailed status of repository
   */
  async status() {
    const result = await this.run("status --porcelain=v1 --branch");
    const lines = result.stdout.trim().split("\n").filter(Boolean);
    const branchLine = lines[0] || "";
    const statusLines = lines.slice(1);
    const branchMatch = branchLine.match(/^## (?:No branch|\S+)(?:\.\.\.\S+)?(?:\s+\[(?:ahead (\d+))?(?:, )?(?:behind (\d+))?\])?/);
    const branch = branchLine.replace(/^## /, "").split("...")[0].split(" ")[0];
    const ahead = (branchMatch == null ? void 0 : branchMatch[1]) ? parseInt(branchMatch[1]) : 0;
    const behind = (branchMatch == null ? void 0 : branchMatch[2]) ? parseInt(branchMatch[2]) : 0;
    const staged = [];
    const modified = [];
    const untracked = [];
    const conflicts = [];
    for (const line of statusLines) {
      const indexStatus = line[0];
      const workTreeStatus = line[1];
      const fileName = line.substring(3);
      if (indexStatus === "U" || workTreeStatus === "U" || indexStatus === "A" && workTreeStatus === "A" || indexStatus === "D" && workTreeStatus === "D") {
        conflicts.push(fileName);
        continue;
      }
      if (indexStatus !== " " && indexStatus !== "?") {
        staged.push(fileName);
      }
      if (workTreeStatus !== " " && workTreeStatus !== "?") {
        modified.push(fileName);
      }
      if (indexStatus === "?" && workTreeStatus === "?") {
        untracked.push(fileName);
      }
    }
    return {
      isRepo: true,
      branch: branch === "HEAD" ? "(detached)" : branch,
      ahead,
      behind,
      staged,
      modified,
      untracked,
      conflicts,
      clean: staged.length === 0 && modified.length === 0 && untracked.length === 0 && conflicts.length === 0
    };
  }
  /**
   * Check if there are any conflicts
   */
  async hasConflicts() {
    try {
      const result = await this.run("diff --name-only --diff-filter=U");
      return result.stdout.trim().length > 0;
    } catch (e) {
      return false;
    }
  }
  /**
   * Add all changes to staging
   */
  async addAll() {
    await this.run("add -A");
  }
  /**
   * Add specific files to staging
   */
  async add(files) {
    if (files.length === 0)
      return;
    const escapedFiles = files.map((f) => `"${f.replace(/"/g, '\\"')}"`).join(" ");
    await this.run(`add ${escapedFiles}`);
  }
  /**
   * Commit changes
   */
  async commit(message) {
    var _a;
    try {
      await this.run(`commit -m "${message.replace(/"/g, '\\"')}"`);
      return { success: true, message: "Commit successful", files: 0 };
    } catch (error) {
      if ((_a = error.stdout) == null ? void 0 : _a.includes("nothing to commit")) {
        return { success: true, message: "Nothing to commit", files: 0 };
      }
      throw error;
    }
  }
  /**
   * Pull from remote
   */
  async pull() {
    try {
      const branch = await this.getCurrentBranch();
      const remote = await this.getRemoteName();
      if (!remote) {
        return { success: false, message: "No remote configured", files: [], conflicts: [] };
      }
      await this.fetch();
      const status = await this.status();
      if (status.modified.length > 0 || status.staged.length > 0) {
        await this.run('stash push -m "obsidian-git-sync-auto-stash"');
      }
      const result = await this.run(`pull ${remote} ${branch} --rebase`);
      try {
        await this.run("stash pop");
      } catch (e) {
      }
      const files = this.parsePullFiles(result.stdout);
      return { success: true, message: "Pull successful", files, conflicts: [] };
    } catch (error) {
      if (await this.hasConflicts()) {
        const conflictFiles = await this.getConflictFiles();
        return {
          success: false,
          message: "Merge conflicts detected",
          files: [],
          conflicts: conflictFiles
        };
      }
      throw error;
    }
  }
  /**
   * Push to remote
   */
  async push() {
    try {
      const branch = await this.getCurrentBranch();
      const remote = await this.getRemoteName();
      if (!remote) {
        return { success: false, message: "No remote configured", pushed: 0 };
      }
      await this.run(`push ${remote} ${branch}`);
      return { success: true, message: "Push successful", pushed: 1 };
    } catch (error) {
      throw error;
    }
  }
  /**
   * Push with --set-upstream flag for new branches
   */
  async pushWithUpstream() {
    try {
      const branch = await this.getCurrentBranch();
      const remote = await this.getRemoteName();
      if (!remote) {
        return { success: false, message: "No remote configured", pushed: 0 };
      }
      await this.run(`push -u ${remote} ${branch}`);
      return { success: true, message: "Push successful", pushed: 1 };
    } catch (error) {
      throw error;
    }
  }
  /**
   * Get list of conflict files
   */
  async getConflictFiles() {
    try {
      const result = await this.run("diff --name-only --diff-filter=U");
      return result.stdout.trim().split("\n").filter(Boolean);
    } catch (e) {
      return [];
    }
  }
  /**
   * Parse files changed from pull output
   */
  parsePullFiles(output) {
    const files = [];
    const lines = output.split("\n");
    for (const line of lines) {
      const match = line.match(/^\s+(.+?)\s*\|/);
      if (match) {
        files.push(match[1].trim());
      }
    }
    return files;
  }
  /**
   * Get log of recent commits
   */
  async log(count = 5) {
    const result = await this.run(`log --oneline -${count}`);
    return result.stdout.trim().split("\n").filter(Boolean);
  }
  /**
   * Check if there's an upstream branch
   */
  async hasUpstream() {
    try {
      const branch = await this.getCurrentBranch();
      await this.run(`rev-parse --abbrev-ref ${branch}@{upstream}`);
      return true;
    } catch (e) {
      return false;
    }
  }
  /**
   * Set upstream branch
   */
  async setUpstream() {
    const branch = await this.getCurrentBranch();
    const remote = await this.getRemoteName();
    if (remote) {
      await this.run(`branch --set-upstream-to=${remote}/${branch}`);
    }
  }
  /**
   * Abort an ongoing rebase
   */
  async abortRebase() {
    await this.run("rebase --abort");
  }
  /**
   * Abort an ongoing merge
   */
  async abortMerge() {
    await this.run("merge --abort");
  }
  /**
   * Configure git user name
   */
  async setUserName(name) {
    await this.run(`config user.name "${name}"`);
  }
  /**
   * Configure git user email
   */
  async setUserEmail(email) {
    await this.run(`config user.email "${email}"`);
  }
  /**
   * Get git user name
   */
  async getUserName() {
    try {
      const result = await this.run("config user.name");
      return result.stdout.trim() || null;
    } catch (e) {
      return null;
    }
  }
  /**
   * Get git user email
   */
  async getUserEmail() {
    try {
      const result = await this.run("config user.email");
      return result.stdout.trim() || null;
    } catch (e) {
      return null;
    }
  }
};

// src/utils/helpers.ts
function formatDate(date = /* @__PURE__ */ new Date()) {
  return date.toISOString().replace(/T/, " ").replace(/\..+/, "");
}
function generateCommitMessage(template) {
  const now = /* @__PURE__ */ new Date();
  return template.replace(/\{\{date\}\}/g, formatDate(now)).replace(/\{\{datetime\}\}/g, formatDate(now)).replace(/\{\{timestamp\}\}/g, now.getTime().toString()).replace(/\{\{isoDate\}\}/g, now.toISOString()).replace(/\{\{time\}\}/g, now.toTimeString().split(" ")[0]);
}

// src/sync/sync-manager.ts
var SyncManager = class {
  constructor(plugin) {
    this.syncLock = false;
    this.autoSyncInterval = null;
    this.onStatusChange = null;
    this.lastSyncTime = null;
    this.lastSyncResult = null;
    this.plugin = plugin;
    this.git = new GitExecutor(plugin.settings.gitPath, this.getVaultPath());
  }
  /**
   * 获取库路径
   */
  getVaultPath() {
    return this.plugin.app.vault.adapter.basePath;
  }
  /**
   * 设置状态变更回调
   */
  setStatusCallback(callback) {
    this.onStatusChange = callback;
  }
  /**
   * 更新状态并通知回调
   */
  updateStatus(status, message) {
    if (this.onStatusChange) {
      this.onStatusChange(status, message);
    }
  }
  /**
   * 检查是否正在同步
   */
  isSyncing() {
    return this.syncLock;
  }
  /**
   * 检查 Git 是否可用且仓库已初始化
   */
  async checkGitStatus() {
    const gitAvailable = await this.git.isGitAvailable();
    if (!gitAvailable) {
      return { available: false, isRepo: false, error: "Git \u672A\u5B89\u88C5\u6216\u672A\u627E\u5230" };
    }
    const isRepo = await this.git.isRepo();
    return { available: true, isRepo };
  }
  /**
   * 初始化仓库
   */
  async initRepo() {
    await this.git.init();
  }
  /**
   * 获取 Git 状态
   */
  async getStatus() {
    return await this.git.status();
  }
  /**
   * 执行完整同步：拉取 → 提交 → 推送
   */
  async sync() {
    if (this.syncLock) {
      return { success: false, message: "\u540C\u6B65\u6B63\u5728\u8FDB\u884C\u4E2D" };
    }
    this.syncLock = true;
    try {
      const { available, isRepo, error } = await this.checkGitStatus();
      if (!available) {
        this.updateStatus("error", error || "Git \u4E0D\u53EF\u7528");
        return { success: false, message: error || "Git \u4E0D\u53EF\u7528" };
      }
      if (!isRepo) {
        this.updateStatus("error", "\u4E0D\u662F Git \u4ED3\u5E93");
        return { success: false, message: "\u4E0D\u662F Git \u4ED3\u5E93\uFF0C\u8BF7\u5148\u521D\u59CB\u5316\u3002" };
      }
      if (await this.git.hasConflicts()) {
        this.updateStatus("conflict", "\u68C0\u6D4B\u5230\u5408\u5E76\u51B2\u7A81");
        return { success: false, message: "\u68C0\u6D4B\u5230\u5408\u5E76\u51B2\u7A81\uFF0C\u8BF7\u624B\u52A8\u89E3\u51B3\u3002", conflicts: [] };
      }
      this.updateStatus("pulling", "\u6B63\u5728\u62C9\u53D6\u66F4\u65B0...");
      const pullResult = await this.pullOnly();
      if (!pullResult.success && pullResult.conflicts.length > 0) {
        this.updateStatus("conflict", "\u68C0\u6D4B\u5230\u5408\u5E76\u51B2\u7A81");
        this.lastSyncResult = { success: false, message: "\u62C9\u53D6\u540E\u5B58\u5728\u5408\u5E76\u51B2\u7A81", conflicts: pullResult.conflicts };
        return this.lastSyncResult;
      }
      this.updateStatus("pushing", "\u6B63\u5728\u63D0\u4EA4\u5E76\u63A8\u9001...");
      const pushResult = await this.commitAndPush();
      if (pushResult.success) {
        this.updateStatus("success", "\u540C\u6B65\u5B8C\u6210");
        this.lastSyncTime = /* @__PURE__ */ new Date();
        this.lastSyncResult = { success: true, message: "\u540C\u6B65\u5B8C\u6210", pulled: pullResult.files.length, pushed: pushResult.pushed };
        return this.lastSyncResult;
      } else {
        this.updateStatus("error", pushResult.message);
        this.lastSyncResult = { success: false, message: pushResult.message };
        return this.lastSyncResult;
      }
    } catch (error) {
      const message = error.message || "\u540C\u6B65\u65F6\u53D1\u751F\u672A\u77E5\u9519\u8BEF";
      this.updateStatus("error", message);
      this.lastSyncResult = { success: false, message };
      return this.lastSyncResult;
    } finally {
      this.syncLock = false;
    }
  }
  /**
   * 从远程拉取更新
   */
  async pullOnly() {
    try {
      const remote = await this.git.getRemoteName();
      if (!remote) {
        return { success: true, message: "\u672A\u914D\u7F6E\u8FDC\u7A0B\u4ED3\u5E93\uFF0C\u8DF3\u8FC7\u62C9\u53D6", files: [], conflicts: [] };
      }
      await this.git.fetch();
      const status = await this.git.status();
      if (status.behind === 0) {
        return { success: true, message: "\u5DF2\u662F\u6700\u65B0", files: [], conflicts: [] };
      }
      this.updateStatus("pulling", "\u6B63\u5728\u62C9\u53D6\u66F4\u65B0...");
      const result = await this.git.pull();
      return result;
    } catch (error) {
      if (await this.git.hasConflicts()) {
        const conflictFiles = await this.getStatus().then((s) => s.conflicts);
        this.updateStatus("conflict", "\u68C0\u6D4B\u5230\u5408\u5E76\u51B2\u7A81");
        return { success: false, message: "\u68C0\u6D4B\u5230\u5408\u5E76\u51B2\u7A81", files: [], conflicts: conflictFiles };
      }
      throw error;
    }
  }
  /**
   * 提交所有更改并推送到远程
   */
  async commitAndPush() {
    var _a;
    try {
      const status = await this.git.status();
      if (status.clean) {
        if (status.ahead > 0) {
          this.updateStatus("pushing", "\u6B63\u5728\u63A8\u9001...");
          return await this.git.push();
        }
        return { success: true, message: "\u6CA1\u6709\u9700\u8981\u63D0\u4EA4\u6216\u63A8\u9001\u7684\u5185\u5BB9", pushed: 0 };
      }
      await this.git.addAll();
      const message = generateCommitMessage(this.plugin.settings.commitMessage);
      await this.git.commit(message);
      const hasUpstream = await this.git.hasUpstream();
      this.updateStatus("pushing", "\u6B63\u5728\u63A8\u9001...");
      if (hasUpstream) {
        return await this.git.push();
      } else {
        return await this.git.pushWithUpstream();
      }
    } catch (error) {
      if ((_a = error.stdout) == null ? void 0 : _a.includes("nothing to commit")) {
        try {
          return await this.git.push();
        } catch (pushError) {
          return { success: false, message: pushError.message, pushed: 0 };
        }
      }
      return { success: false, message: error.message, pushed: 0 };
    }
  }
  /**
   * 获取上次同步结果
   */
  getLastSyncResult() {
    return this.lastSyncResult;
  }
  /**
   * 获取上次同步时间
   */
  getLastSyncTime() {
    return this.lastSyncTime;
  }
  /**
   * 启动自动同步
   */
  startAutoSync() {
    if (this.autoSyncInterval !== null) {
      this.stopAutoSync();
    }
    const intervalMs = this.plugin.settings.syncInterval * 60 * 1e3;
    this.autoSyncInterval = window.setInterval(() => {
      this.sync().catch((error) => {
        console.error("\u81EA\u52A8\u540C\u6B65\u9519\u8BEF:", error);
      });
    }, intervalMs);
    this.plugin.registerInterval(this.autoSyncInterval);
  }
  /**
   * 停止自动同步
   */
  stopAutoSync() {
    if (this.autoSyncInterval !== null) {
      window.clearInterval(this.autoSyncInterval);
      this.autoSyncInterval = null;
    }
  }
  /**
   * 重启自动同步（设置变更后使用）
   */
  restartAutoSync() {
    if (this.plugin.settings.autoSync) {
      this.stopAutoSync();
      this.startAutoSync();
    } else {
      this.stopAutoSync();
    }
  }
  /**
   * 初始化同步管理器
   */
  async initialize() {
    const { available, isRepo } = await this.checkGitStatus();
    if (!available) {
      this.updateStatus("error", "Git \u4E0D\u53EF\u7528");
      return;
    }
    if (!isRepo) {
      this.updateStatus("error", "\u4E0D\u662F Git \u4ED3\u5E93");
      return;
    }
    if (this.plugin.settings.autoPullOnStart) {
      try {
        await this.pullOnly();
      } catch (error) {
        console.error("\u81EA\u52A8\u62C9\u53D6\u9519\u8BEF:", error);
      }
    }
    if (this.plugin.settings.autoSync) {
      this.startAutoSync();
    }
    this.updateStatus("idle", "\u5C31\u7EEA");
  }
  /**
   * 销毁同步管理器
   */
  dispose() {
    this.stopAutoSync();
  }
};

// src/ui/status-bar.ts
var import_obsidian = require("obsidian");
var StatusBar = class {
  constructor(plugin) {
    this.statusBarEl = null;
    this.iconEl = null;
    this.textEl = null;
    this.plugin = plugin;
  }
  /**
   * 初始化状态栏
   */
  initialize() {
    if (!this.plugin.settings.showStatusBar) {
      return;
    }
    this.statusBarEl = this.plugin.addStatusBarItem();
    this.statusBarEl.addClass("git-sync-status-bar");
    this.iconEl = this.statusBarEl.createSpan({ cls: "git-sync-status-icon" });
    this.textEl = this.statusBarEl.createSpan({ cls: "git-sync-status-text" });
    this.statusBarEl.addEventListener("click", () => {
      this.plugin.sync();
    });
    this.updateStatus("idle", "\u5C31\u7EEA");
  }
  /**
   * 更新状态栏显示
   */
  updateStatus(status, message) {
    if (!this.statusBarEl || !this.iconEl || !this.textEl) {
      return;
    }
    this.statusBarEl.removeClass("syncing");
    this.statusBarEl.removeClass("error");
    this.statusBarEl.removeClass("success");
    this.statusBarEl.removeClass("conflict");
    switch (status) {
      case "idle":
        (0, import_obsidian.setIcon)(this.iconEl, "git-branch");
        this.textEl.setText(message || "\u5C31\u7EEA");
        break;
      case "syncing":
        this.statusBarEl.addClass("syncing");
        (0, import_obsidian.setIcon)(this.iconEl, "sync");
        this.textEl.setText(message || "\u540C\u6B65\u4E2D...");
        break;
      case "pulling":
        this.statusBarEl.addClass("syncing");
        (0, import_obsidian.setIcon)(this.iconEl, "arrow-down");
        this.textEl.setText(message || "\u62C9\u53D6\u4E2D...");
        break;
      case "pushing":
        this.statusBarEl.addClass("syncing");
        (0, import_obsidian.setIcon)(this.iconEl, "arrow-up");
        this.textEl.setText(message || "\u63A8\u9001\u4E2D...");
        break;
      case "committing":
        this.statusBarEl.addClass("syncing");
        (0, import_obsidian.setIcon)(this.iconEl, "check");
        this.textEl.setText(message || "\u63D0\u4EA4\u4E2D...");
        break;
      case "success":
        this.statusBarEl.addClass("success");
        (0, import_obsidian.setIcon)(this.iconEl, "check-circle");
        this.textEl.setText(message || "\u540C\u6B65\u5B8C\u6210");
        setTimeout(() => {
          if (this.statusBarEl && this.statusBarEl.hasClass("success")) {
            this.updateStatus("idle", "\u5C31\u7EEA");
          }
        }, 3e3);
        break;
      case "error":
        this.statusBarEl.addClass("error");
        (0, import_obsidian.setIcon)(this.iconEl, "alert-circle");
        this.textEl.setText(message || "\u9519\u8BEF");
        break;
      case "conflict":
        this.statusBarEl.addClass("conflict");
        (0, import_obsidian.setIcon)(this.iconEl, "alert-triangle");
        this.textEl.setText(message || "\u6709\u51B2\u7A81");
        break;
    }
  }
  /**
   * 显示状态栏
   */
  show() {
    if (this.statusBarEl) {
      this.statusBarEl.style.display = "flex";
    }
  }
  /**
   * 隐藏状态栏
   */
  hide() {
    if (this.statusBarEl) {
      this.statusBarEl.style.display = "none";
    }
  }
  /**
   * 销毁状态栏
   */
  destroy() {
    if (this.statusBarEl) {
      this.statusBarEl.remove();
      this.statusBarEl = null;
      this.iconEl = null;
      this.textEl = null;
    }
  }
};

// src/ui/settings-tab.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  autoSync: false,
  syncInterval: 10,
  commitMessage: "\u5E93\u5907\u4EFD: {{date}}",
  autoPullOnStart: true,
  showStatusBar: true,
  gitPath: "git",
  excludePatterns: [],
  showNotifications: true
};
var GitSyncSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("git-sync-settings");
    containerEl.createEl("h2", { text: "Git \u540C\u6B65\u8BBE\u7F6E" });
    this.createStatusSection();
    containerEl.createEl("h3", { text: "\u540C\u6B65\u8BBE\u7F6E" });
    new import_obsidian2.Setting(containerEl).setName("\u81EA\u52A8\u540C\u6B65").setDesc("\u542F\u7528\u5B9A\u65F6\u81EA\u52A8\u540C\u6B65").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoSync).onChange(async (value) => {
      this.plugin.settings.autoSync = value;
      await this.plugin.saveSettings();
      this.plugin.restartAutoSync();
    }));
    new import_obsidian2.Setting(containerEl).setName("\u540C\u6B65\u95F4\u9694").setDesc("\u81EA\u52A8\u540C\u6B65\u7684\u65F6\u95F4\u95F4\u9694\uFF08\u5206\u949F\uFF09").addText((text) => text.setValue(String(this.plugin.settings.syncInterval)).setPlaceholder("10").onChange(async (value) => {
      const num = parseInt(value);
      if (!isNaN(num) && num >= 1) {
        this.plugin.settings.syncInterval = num;
        await this.plugin.saveSettings();
        this.plugin.restartAutoSync();
      }
    }));
    new import_obsidian2.Setting(containerEl).setName("\u542F\u52A8\u65F6\u62C9\u53D6").setDesc("Obsidian \u542F\u52A8\u65F6\u81EA\u52A8\u62C9\u53D6\u8FDC\u7A0B\u66F4\u65B0").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoPullOnStart).onChange(async (value) => {
      this.plugin.settings.autoPullOnStart = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u63D0\u4EA4\u8BBE\u7F6E" });
    new import_obsidian2.Setting(containerEl).setName("\u63D0\u4EA4\u6D88\u606F").setDesc("\u63D0\u4EA4\u6D88\u606F\u6A21\u677F\uFF0C\u652F\u6301: {{date}}, {{time}}, {{datetime}}").addText((text) => text.setValue(this.plugin.settings.commitMessage).setPlaceholder("\u5E93\u5907\u4EFD: {{date}}").onChange(async (value) => {
      this.plugin.settings.commitMessage = value || DEFAULT_SETTINGS.commitMessage;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u663E\u793A\u8BBE\u7F6E" });
    new import_obsidian2.Setting(containerEl).setName("\u663E\u793A\u72B6\u6001\u680F").setDesc("\u5728\u72B6\u6001\u680F\u663E\u793A\u540C\u6B65\u72B6\u6001").addToggle((toggle) => toggle.setValue(this.plugin.settings.showStatusBar).onChange(async (value) => {
      this.plugin.settings.showStatusBar = value;
      await this.plugin.saveSettings();
      this.plugin.updateStatusBarVisibility();
    }));
    new import_obsidian2.Setting(containerEl).setName("\u663E\u793A\u901A\u77E5").setDesc("\u663E\u793A\u540C\u6B65\u4E8B\u4EF6\u7684\u901A\u77E5").addToggle((toggle) => toggle.setValue(this.plugin.settings.showNotifications).onChange(async (value) => {
      this.plugin.settings.showNotifications = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Git \u8BBE\u7F6E" });
    new import_obsidian2.Setting(containerEl).setName("Git \u8DEF\u5F84").setDesc("Git \u53EF\u6267\u884C\u6587\u4EF6\u8DEF\u5F84\uFF0C\u9ED8\u8BA4\u4F7F\u7528\u7CFB\u7EDF PATH \u4E2D\u7684 git").addText((text) => text.setValue(this.plugin.settings.gitPath).setPlaceholder("git").onChange(async (value) => {
      this.plugin.settings.gitPath = value || DEFAULT_SETTINGS.gitPath;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u64CD\u4F5C" });
    new import_obsidian2.Setting(containerEl).setName("\u7ACB\u5373\u540C\u6B65").setDesc("\u6267\u884C\u5B8C\u6574\u540C\u6B65\uFF08\u62C9\u53D6 \u2192 \u63D0\u4EA4 \u2192 \u63A8\u9001\uFF09").addButton((button) => button.setButtonText("\u540C\u6B65").setCta().onClick(async () => {
      await this.plugin.sync();
    }));
    new import_obsidian2.Setting(containerEl).setName("\u62C9\u53D6\u66F4\u65B0").setDesc("\u4ECE\u8FDC\u7A0B\u4ED3\u5E93\u62C9\u53D6\u66F4\u65B0").addButton((button) => button.setButtonText("\u62C9\u53D6").onClick(async () => {
      await this.plugin.pull();
    }));
    new import_obsidian2.Setting(containerEl).setName("\u63D0\u4EA4\u5E76\u63A8\u9001").setDesc("\u63D0\u4EA4\u6240\u6709\u66F4\u6539\u5E76\u63A8\u9001\u5230\u8FDC\u7A0B").addButton((button) => button.setButtonText("\u63A8\u9001").onClick(async () => {
      await this.plugin.commitAndPush();
    }));
    containerEl.createEl("h3", { text: "\u5E2E\u52A9" });
    const helpDiv = containerEl.createDiv();
    helpDiv.innerHTML = `
      <p>\u6B64\u63D2\u4EF6\u901A\u8FC7 Git \u540C\u6B65\u4F60\u7684\u5E93\u3002</p>
      <p><strong>\u524D\u7F6E\u6761\u4EF6\uFF1A</strong></p>
      <ul>
        <li>\u7CFB\u7EDF\u5DF2\u5B89\u88C5 Git</li>
        <li>\u5E93\u5DF2\u521D\u59CB\u5316\u4E3A Git \u4ED3\u5E93 (git init)</li>
        <li>\u5DF2\u914D\u7F6E\u8FDC\u7A0B\u4ED3\u5E93 (git remote add origin &lt;url&gt;)</li>
        <li>\u5DF2\u914D\u7F6E Git \u51ED\u8BC1</li>
      </ul>
      <p><strong>\u6CE8\u610F\uFF1A</strong>\u6B64\u63D2\u4EF6\u4EC5\u652F\u6301\u684C\u9762\u7AEF\uFF08Windows\u3001macOS\u3001Linux\uFF09\u3002</p>
    `;
  }
  /**
   * 创建状态区域
   */
  createStatusSection() {
    const { containerEl } = this;
    const statusContainer = containerEl.createDiv({ cls: "status-container" });
    statusContainer.createEl("h4", { text: "\u4ED3\u5E93\u72B6\u6001" });
    this.checkGitStatus(statusContainer);
  }
  /**
   * 检查并显示 Git 状态
   */
  async checkGitStatus(container) {
    const gitAvailable = await this.plugin.isGitAvailable();
    const isRepo = await this.plugin.isRepo();
    const items = [
      { label: "Git \u5DF2\u5B89\u88C5", value: gitAvailable ? "\u662F" : "\u5426", status: gitAvailable ? "success" : "error" },
      { label: "Git \u4ED3\u5E93", value: isRepo ? "\u662F" : "\u5426", status: isRepo ? "success" : "error" }
    ];
    if (isRepo) {
      try {
        const status = await this.plugin.getGitStatus();
        items.push({
          label: "\u5F53\u524D\u5206\u652F",
          value: status.branch,
          status: "normal"
        });
        items.push({
          label: "\u66F4\u6539",
          value: status.clean ? "\u65E0" : `${status.staged.length + status.modified.length + status.untracked.length} \u4E2A\u6587\u4EF6`,
          status: status.clean ? "success" : "warning"
        });
      } catch (error) {
        items.push({
          label: "\u72B6\u6001",
          value: "\u8BFB\u53D6\u5931\u8D25",
          status: "error"
        });
      }
    }
    for (const item of items) {
      const itemEl = container.createDiv({ cls: "status-item" });
      itemEl.createSpan({ cls: "status-label", text: item.label });
      itemEl.createSpan({ cls: `status-value ${item.status}`, text: item.value });
    }
  }
};

// main.ts
var GitSyncPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    console.log("\u52A0\u8F7D Git \u540C\u6B65\u63D2\u4EF6");
    await this.loadSettings();
    this.git = new GitExecutor(this.settings.gitPath, this.getVaultPath());
    this.statusBar = new StatusBar(this);
    this.statusBar.initialize();
    this.syncManager = new SyncManager(this);
    this.syncManager.setStatusCallback((status, message) => {
      this.statusBar.updateStatus(status, message);
    });
    this.addSettingTab(new GitSyncSettingTab(this.app, this));
    this.registerCommands();
    this.addRibbonIcon("git-branch", "Git \u540C\u6B65", () => {
      this.sync();
    });
    await this.syncManager.initialize();
  }
  onunload() {
    console.log("\u5378\u8F7D Git \u540C\u6B65\u63D2\u4EF6");
    this.syncManager.dispose();
    this.statusBar.destroy();
  }
  /**
   * 获取库路径
   */
  getVaultPath() {
    return this.app.vault.adapter.basePath;
  }
  /**
   * 加载设置
   */
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  /**
   * 保存设置
   */
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /**
   * 注册命令
   */
  registerCommands() {
    this.addCommand({
      id: "git-sync",
      name: "\u540C\u6B65",
      callback: () => this.sync()
    });
    this.addCommand({
      id: "git-pull",
      name: "\u62C9\u53D6\u66F4\u65B0",
      callback: () => this.pull()
    });
    this.addCommand({
      id: "git-push",
      name: "\u63D0\u4EA4\u5E76\u63A8\u9001",
      callback: () => this.commitAndPush()
    });
    this.addCommand({
      id: "git-status",
      name: "\u663E\u793A\u72B6\u6001",
      callback: () => this.showStatus()
    });
    this.addCommand({
      id: "git-init",
      name: "\u521D\u59CB\u5316\u4ED3\u5E93",
      callback: () => this.initRepo()
    });
  }
  /**
   * 执行完整同步
   */
  async sync() {
    if (this.syncManager.isSyncing()) {
      this.showNotice("\u540C\u6B65\u6B63\u5728\u8FDB\u884C\u4E2D");
      return;
    }
    this.showNotice("\u5F00\u59CB\u540C\u6B65...");
    const result = await this.syncManager.sync();
    if (result.success) {
      this.showNotice(result.message);
    } else {
      this.showNotice(`\u540C\u6B65\u5931\u8D25: ${result.message}`, true);
    }
  }
  /**
   * 拉取更新
   */
  async pull() {
    if (this.syncManager.isSyncing()) {
      this.showNotice("\u540C\u6B65\u6B63\u5728\u8FDB\u884C\u4E2D");
      return;
    }
    const result = await this.syncManager.pullOnly();
    if (result.success) {
      this.showNotice(result.message);
    } else {
      this.showNotice(`\u62C9\u53D6\u5931\u8D25: ${result.message}`, true);
    }
  }
  /**
   * 提交并推送
   */
  async commitAndPush() {
    if (this.syncManager.isSyncing()) {
      this.showNotice("\u540C\u6B65\u6B63\u5728\u8FDB\u884C\u4E2D");
      return;
    }
    const result = await this.syncManager.commitAndPush();
    if (result.success) {
      this.showNotice(result.message);
    } else {
      this.showNotice(`\u63A8\u9001\u5931\u8D25: ${result.message}`, true);
    }
  }
  /**
   * 显示 Git 状态
   */
  async showStatus() {
    const { available, isRepo, error } = await this.checkGitStatus();
    if (!available) {
      this.showNotice(`Git \u4E0D\u53EF\u7528: ${error}`, true);
      return;
    }
    if (!isRepo) {
      this.showNotice('\u4E0D\u662F Git \u4ED3\u5E93\uFF0C\u8BF7\u4F7F\u7528"\u521D\u59CB\u5316\u4ED3\u5E93"\u547D\u4EE4\u521B\u5EFA\u3002', true);
      return;
    }
    const status = await this.getGitStatus();
    const lines = [];
    lines.push(`\u5206\u652F: ${status.branch}`);
    if (status.clean) {
      lines.push("\u72B6\u6001: \u5E72\u51C0");
    } else {
      if (status.staged.length > 0) {
        lines.push(`\u5DF2\u6682\u5B58: ${status.staged.length} \u4E2A\u6587\u4EF6`);
      }
      if (status.modified.length > 0) {
        lines.push(`\u5DF2\u4FEE\u6539: ${status.modified.length} \u4E2A\u6587\u4EF6`);
      }
      if (status.untracked.length > 0) {
        lines.push(`\u672A\u8DDF\u8E2A: ${status.untracked.length} \u4E2A\u6587\u4EF6`);
      }
      if (status.conflicts.length > 0) {
        lines.push(`\u51B2\u7A81: ${status.conflicts.length} \u4E2A\u6587\u4EF6`);
      }
    }
    if (status.ahead > 0) {
      lines.push(`\u9886\u5148: ${status.ahead} \u4E2A\u63D0\u4EA4`);
    }
    if (status.behind > 0) {
      lines.push(`\u843D\u540E: ${status.behind} \u4E2A\u63D0\u4EA4`);
    }
    this.showNotice(lines.join("\n"));
  }
  /**
   * 初始化仓库
   */
  async initRepo() {
    const { isRepo } = await this.checkGitStatus();
    if (isRepo) {
      this.showNotice("\u5DF2\u7ECF\u662F Git \u4ED3\u5E93");
      return;
    }
    try {
      await this.git.init();
      this.showNotice("Git \u4ED3\u5E93\u5DF2\u521D\u59CB\u5316");
    } catch (error) {
      this.showNotice(`\u521D\u59CB\u5316\u5931\u8D25: ${error.message}`, true);
    }
  }
  /**
   * 检查 Git 状态
   */
  async checkGitStatus() {
    const available = await this.git.isGitAvailable();
    if (!available) {
      return { available: false, isRepo: false, error: "Git \u672A\u5B89\u88C5\u6216\u672A\u627E\u5230" };
    }
    const isRepo = await this.git.isRepo();
    return { available: true, isRepo };
  }
  /**
   * 检查 Git 是否可用
   */
  async isGitAvailable() {
    return await this.git.isGitAvailable();
  }
  /**
   * 检查是否为 Git 仓库
   */
  async isRepo() {
    return await this.git.isRepo();
  }
  /**
   * 获取 Git 状态
   */
  async getGitStatus() {
    return await this.git.status();
  }
  /**
   * 重启自动同步
   */
  restartAutoSync() {
    this.syncManager.restartAutoSync();
  }
  /**
   * 更新状态栏可见性
   */
  updateStatusBarVisibility() {
    if (this.settings.showStatusBar) {
      this.statusBar.show();
    } else {
      this.statusBar.hide();
    }
  }
  /**
   * 显示通知
   */
  showNotice(message, isError = false) {
    if (!this.settings.showNotifications) {
      return;
    }
    if (isError) {
      new import_obsidian3.Notice(`Git \u540C\u6B65: ${message}`, 5e3);
    } else {
      new import_obsidian3.Notice(`Git \u540C\u6B65: ${message}`);
    }
  }
};
